---
mysql_root_password: "root"
default_owner: "abarmin"

nextcloud_database_name: "nextcloud"
nextcloud_database_user: "nextcloud"
nextcloud_database_password: "nextcloud_password"

apache_user: "www-data"
apache_group: "www-data"

nfs_allowed_network: "192.168.88.0/24"

jellyfin_source_movies: "/tank/nas/nextcloud/data/admin/files/Videos/Movies"
jellyfin_source_series: "/tank/nas/nextcloud/data/admin/files/Videos/TV-Series"
jellyfin_source_anime: "/tank/nas/nextcloud/data/admin/files/Videos/Anime"
jellyfin_source_cartoons: "/tank/nas/nextcloud/data/admin/files/Videos/Cartoons"
jellyfin_target_movies: "/mnt/jellyfin/movies"
jellyfin_target_series: "/mnt/jellyfin/series"
jellyfin_target_anime: "/mnt/jellyfin/anime"
jellyfin_target_cartoons: "/mnt/jellyfin/cartoons"
jellyfin_user: "jellyfin"
jellyfin_group: "jellyfin"
